name: specwrk

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.4.4"
          - "3.3.0"
          - "3.2.0"
          - "3.1.0"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Standard
        run: bundle exec rake standard
      
      - name: RSpec
        run: bundle exec rspec
